# Linear Algebra

In [1]:
import torch

## Scalars

In [3]:
# scalar : tensors that contain only one element
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors

In [5]:
# row vector
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
# element
x[2]

tensor(2)

In [7]:
# tensor's length == the dimensionality of the vector
len(x)

3

In [8]:
# shape is a tuple that indicates a tensor’s length along each axis
x.shape

torch.Size([3])

## Matrices

In [9]:
# convert any appropriately sized (m x n) tensor into an (m, n) matrix
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
# flip the axes
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
# symmetric matrix
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## Tensors

In [12]:
# 3rd order tensor
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Basic Properties of Tensor Arithmetic

In [13]:
# clone : copy of tensor by allocating new memory
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [14]:
# Hadamard product : elementwise product
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [15]:
# compute a scalar and a tensor (broadcasting)
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reduction

In [16]:
# sum of vector
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [18]:
# sum of matrix
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [23]:
# sum function reduces a tensor
# axis 0 / 1 : sum over all elements along the rows / columns
print(A.shape, A.sum(axis=0).shape)
print(A.shape, A.sum(axis=1).shape)
print(A.sum(axis=[0, 1]) == A.sum())

torch.Size([2, 3]) torch.Size([3])
torch.Size([2, 3]) torch.Size([2])
tensor(True)


In [25]:
# mean : average
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [26]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

## Non-Reduction Sum

In [29]:
# keep the number of axes
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [30]:
# broadcast
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [33]:
# calculate the cumulative sum of elements along some axis
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## Dot Products

In [34]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [35]:
torch.sum(x * y)

tensor(3.)

In [36]:
# Matrix-Vector Product
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [40]:
# Matrix-Matrix Product
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## Norms

In [41]:
# l2 norm : Euclidean length of a vector
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [42]:
# l1 norm : Manhattan Distance
torch.abs(u).sum()

tensor(7.)

In [43]:
# Frobenius Norm : l2 norm of matrix
torch.norm(torch.ones((4, 9)))

tensor(6.)